Repository erwindon/SaltGUI, pull requests merged in 2018-12, with the labels that each got.

#85 Nodegroup
  README.MD
  saltgui/static/scripts/api.js
  saltgui/static/scripts/commandbox.js
  saltgui/static/scripts/routes/minions.js
  saltgui/static/scripts/targettype.js
Labels: new-feature, work-in-progress

#94 ignore error from the login-session-check
  saltgui/static/scripts/api.js
Labels: bug, work-in-progress

#95 add a few simple commands for grains
  saltgui/index.html
  saltgui/static/scripts/commandbox.js
  saltgui/static/scripts/routes/grainsminion.js
  saltgui/static/scripts/routes/page.js
Labels: enhancement, work-in-progress

#96 add a few simple commands for schedules
  saltgui/index.html
  saltgui/static/scripts/commandbox.js
  saltgui/static/scripts/routes/page.js
  saltgui/static/scripts/routes/schedules.js
  saltgui/static/scripts/routes/schedulesminion.js
Labels: enhancement, work-in-progress

#101 Fix authentication failures for some commands when using docker
  docker/conf/master
Labels: bug, work-in-progress

#102 improvement for pillar information are not always secret
  README.MD
  saltgui/static/scripts/routes/minions.js
  saltgui/static/scripts/routes/pillarsminion.js
Labels: enhancement, work-in-progress

#120 Hardcode docker container hostname #119
  docker/docker-compose.yml
Labels: enhancement, work-in-progress
